# Generated by Django 4.2.6 on 2023-10-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logging",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("requested_date", models.DateTimeField(auto_now_add=True)),
                ("source_ip", models.GenericIPAddressField()),
                ("request_data", models.JSONField()),
                ("response_data", models.JSONField()),
            ],
        ),
    ]
